#cloud-config

coreos:
  update:
    reboot-strategy: off
users:
  - name: platform
    # Change this! see: https://github.com/coreos/coreos-cloudinit/raw/master/Documentation/cloud-config.md#generating-a-password-hash
    passwd: $1$C3IPO/Q4$rh9psb.DS/2exW4mXaek50
    groups:
      - sudo
      - docker